import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import topImage from "../public/top.png";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Couplen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src={topImage}
          width={300}
          height={300}
          style={{ marginBottom: 30 }}
        />
        <h1 className={styles.title}>Couplen</h1>

        <div className={styles.grid}>
          <a>
            <h2
              onClick={() => router.push("/privacy")}
              style={{ color: "blue" }}
            >
              プライバシーポリシー
            </h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a target="_blank" rel="noopener noreferrer">
          Created by Rai Miura, Takahide Sato
        </a>
      </footer>
    </div>
  );
};

export default Home;
